environment:
  matrix:
    - PYTHON: C:\Python37-x64
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python34-x64
    - PYTHON: C:\Python27-x64

init:
  - SET PATH=%PYTHON%;%PATH%

install:
  - python -m pip install -r requirements.txt
  - python -m pip install -r requirements-dev.txt

build: false

test_script:
  - python -m pytest

cache:
  - '%LOCALAPPDATA%\pip\Cache'
